### ISSUE TITLE
Allow extending a list of translation helpers for AST analysis

### ISSUE THREAD

**Issue by lolmaus** [mainmatter/ember-intl-analyzer#615]
In a project, I have implemented a `t-error` helper to standardize error handling:

Before: 

```hbs
{{#if (eq error.status 403)}}
  {{t "errors.forbidden"}}
{{else if (gte error.status 400}}
  {{t "errors.server-failure"}}
{{else}}
  {{t "my-component.error-message"}}
{{/if}}
```

After:

```hbs
{{t-error error "my-component.error-message"}}
```

Unfortunately, this forces me to add all fallback keys to `ember-intl-analyzer` whitelist.

I would like to configure `ember-intl-analyzer` to recognize my `t-error` helper. I imagine something like this:

```js
export default {
  whitelist: [
    /^[^.]+\.warnings\.[^.]+$/,
  ],
  helpers: ['t', 't-error'],
};
```

Is it something we want to support?

PS Please note this should not be sensitive to argument order.

CC @nickschot

**Comment by Mikek2252** [comment]
This is now available to use in 4.6.0
